### ISSUE TITLE
Select with options return selected value instead of key

### ISSUE THREAD

**Issue by BarnabeD** [fractaledmind/prompts#1]
Passing options as hash on select return selected value instead of key
In the documentation : 
`You may also pass a hash to the options argument to have the selected key returned instead of its value`

I try the README example in my app (I have a User with “owner” role)

```ruby
User.where(role: "owner").exists?
# => true

role = Prompts::SelectPrompt.ask(
  label: "What role should the user have?",
  options: {
    member: "Member",
    contributor: "Contributor",
    owner: "Owner",
  },
  validate: ->(value) do
    if value == "owner" && User.where(role: "owner").exists?
      "An owner already exists."
    end
  end
 ```
then, select the third choice :
<pre>

   <b>What role should the user have?</b> <em>(Enter the number of your choice)</em>
   <b>The role may be changed at any time.</b>
   <b>1.</b> Member
   <b>2.</b> Contributor
   <b>3.</b> Owner

   <b>></b> 3|
</pre>
And return this :
```ruby
#=> "Owner"

role
=> "Owner"
```

As the value "Owner" is returned, the validation doesn't trigger the existing "owner"

**Comment by fractaledmind** [comment]
Yep. Good catch. Fixed with version 0.2.1 with commit b3eba2f
