### ISSUE TITLE
Is there a way to persist the console?

### ISSUE THREAD

**Issue by KonnorRogers** [fractaledmind/prompts#5]
Its quite jarring the way it clears the console on every input. Is there a way to disable clearing the console between responses?

**Comment by fractaledmind** [comment]
What are you imagining? Simply appending "screens"? Scrolling the "screen" to the top, but allowing to scroll back up? Something else?

**Comment by KonnorRogers** [comment]
> What are you imagining? Simply appending "screens"? Scrolling the "screen" to the top, but allowing to scroll back up? Something else?

In my head, appending screens like a typical CLI so I can scroll up and see my previous responses.

 I hadn't thought about scrolling the current view to the top of the viewport, but still allow a user to scroll up and see previous screens but that could be reasonable.

**Comment by fractaledmind** [comment]
I can do this by changing `erase_down` in the `Content` class from `OUTPUT.print "\e[J"` to `OUTPUT.print "\e[2J\e[H"`. I much prefer scrolling the current view to the top of the viewport, such that the user experience is the same, but I can see why allowing you to scroll up to see past screens is useful. I will make this change.
